# Generated by Django 3.1.3 on 2020-11-15 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sponsor',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='shelter.sponsor'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Animal_sponsor',
        ),
    ]
