# Generated by Django 3.1.3 on 2020-11-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='sponsored',
            field=models.IntegerField(default=0),
        ),
    ]
