# Generated by Django 3.1.3 on 2020-12-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_animal_sponsors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='N° de Chip'),
        ),
    ]
