# Generated by Django 3.1.3 on 2020-12-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_auto_20201206_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='animal',
            name='sterilized',
            field=models.CharField(blank=True, max_length=50, verbose_name='Esterilizado'),
        ),
    ]
