# Generated by Django 3.1.3 on 2020-12-09 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0004_auto_20201208_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal_sponsor',
            options={'verbose_name': 'Apadrinamiento', 'verbose_name_plural': 'Apadrinamientos'},
        ),
        migrations.AlterField(
            model_name='animal_sponsor',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='animal_sponsor',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.sponsor', verbose_name='Apadrinamiento'),
        ),
    ]
