# Generated by Django 3.1.3 on 2020-11-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0004_animal_sponsor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-created'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Animales'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'Apadrinamiento', 'verbose_name_plural': 'Apadrinamientos'},
        ),
        migrations.RemoveField(
            model_name='animal',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='animal',
            name='sponsors',
            field=models.ManyToManyField(to='shelter.Sponsor', verbose_name='Apadrinamientos'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='Updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='lifestage',
            field=models.CharField(max_length=50, verbose_name='Etapa de vida'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='cost',
            field=models.IntegerField(verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Identificación'),
        ),
    ]
