# Generated by Django 3.1.3 on 2020-12-09 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0005_auto_20201208_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal_sponsor',
            options={'verbose_name': 'Apadrinamiento de animal', 'verbose_name_plural': 'Apadrinamientos de animales'},
        ),
    ]
