# Generated by Django 3.1.3 on 2020-11-16 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0005_auto_20201116_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal_sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.animal')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.sponsor')),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='sponsors',
            field=models.ManyToManyField(through='shelter.Animal_sponsor', to='shelter.Sponsor', verbose_name='Apadrinamientos'),
        ),
    ]
