# Generated by Django 3.1.3 on 2020-11-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0006_auto_20201116_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='sponsors',
            field=models.ManyToManyField(to='shelter.Sponsor', verbose_name='Apadrinamientos'),
        ),
        migrations.DeleteModel(
            name='Animal_sponsor',
        ),
    ]
