# Generated by Django 3.1.3 on 2020-11-16 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0007_auto_20201116_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='sponsors',
        ),
    ]
