# Generated by Django 3.1.3 on 2020-11-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0008_remove_animal_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sponsors',
            field=models.ManyToManyField(to='shelter.Sponsor', verbose_name='Apadrinamientos'),
        ),
    ]
