# Generated by Django 3.1.3 on 2020-11-16 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0009_animal_sponsors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
