# Generated by Django 3.1.3 on 2020-11-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0012_auto_20201116_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='Updated',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(upload_to='Animales', verbose_name='Imagen'),
        ),
    ]
