# Generated by Django 3.1.3 on 2020-11-24 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_animal_sponsors'),
        ('registration', '0002_auto_20201121_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fname',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lname',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.CreateModel(
            name='Profile_sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.profile')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.sponsor')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='sponsorsToAnimals',
            field=models.ManyToManyField(through='registration.Profile_sponsor', to='shelter.Sponsor', verbose_name='ApadrinamientosAAnimales'),
        ),
    ]
