# Generated by Django 3.1.3 on 2020-11-24 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_animal_sponsors'),
        ('registration', '0003_auto_20201123_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.IntegerField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.animal')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile_sponsor',
        ),
        migrations.AlterField(
            model_name='profile',
            name='sponsorsToAnimals',
            field=models.ManyToManyField(through='registration.Profile_animal', to='shelter.Animal', verbose_name='ApadrinamientosAAnimales'),
        ),
    ]
