# Generated by Django 3.1.3 on 2020-12-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20201123_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='Perfiles', verbose_name='Imagen'),
        ),
    ]
