# Generated by Django 3.1.3 on 2020-12-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20201209_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cargo'),
        ),
    ]
